/*
 * PanelContador.java
 *
 * Created on 30 de enero de 2011, 02:45 PM
 */

package hilocontador;
import javax.swing.*;
/**
 *
 * @author  Angel
 */
public class PanelContador extends javax.swing.JPanel {
    private HiloContador hilo1;
    /** Creates new form PanelContador */
    public PanelContador() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        inicializacion_lbl = new javax.swing.JLabel();
        inicializacion_txt = new javax.swing.JTextField();
        tope_lbl = new javax.swing.JLabel();
        tope_txt = new javax.swing.JTextField();
        igual_lbl = new javax.swing.JLabel();
        valor_txt = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        iniciarDetener_btn = new javax.swing.JButton();
        pausaReanuda_btn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panel1.setLayout(new java.awt.GridLayout(1, 0));

        inicializacion_lbl.setText("Inicializacion");
        panel1.add(inicializacion_lbl);

        inicializacion_txt.setColumns(5);
        inicializacion_txt.setText(" ");
        inicializacion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializacion_txtActionPerformed(evt);
            }
        });
        panel1.add(inicializacion_txt);

        tope_lbl.setText(" Tope");
        panel1.add(tope_lbl);

        tope_txt.setColumns(5);
        tope_txt.setText(" ");
        panel1.add(tope_txt);

        igual_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        igual_lbl.setText("=");
        panel1.add(igual_lbl);

        valor_txt.setColumns(5);
        valor_txt.setEnabled(false);
        panel1.add(valor_txt);

        add(panel1, java.awt.BorderLayout.CENTER);

        panel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        iniciarDetener_btn.setText("Iniciar");
        iniciarDetener_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarDetener_btnActionPerformed(evt);
            }
        });
        panel2.add(iniciarDetener_btn);

        pausaReanuda_btn.setText("Pausar");
        pausaReanuda_btn.setEnabled(false);
        pausaReanuda_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaReanuda_btnActionPerformed(evt);
            }
        });
        panel2.add(pausaReanuda_btn);

        add(panel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void iniciarDetener_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarDetener_btnActionPerformed
// TODO add your handling code here:
    if ( iniciarDetener_btn.getText().equals("Iniciar")){
       
            System.out.println("33");
            int inicio = Integer.parseInt(inicializacion_txt.getText().trim());
            int tope = Integer.parseInt( tope_txt.getText().trim());
            System.out.println("" + inicio + ";" + tope);
            hilo1 = new HiloContador("", inicio,tope, valor_txt);
            hilo1.start();
            iniciarDetener_btn.setText("Detener");
            pausaReanuda_btn.setEnabled(true);
    }else{
        if(hilo1 != null){
            hilo1.setDetenido(true);
            hilo1 = null;
            pausaReanuda_btn.setEnabled(false);
            iniciarDetener_btn.setEnabled(false);
        }
    }
}//GEN-LAST:event_iniciarDetener_btnActionPerformed

private void pausaReanuda_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaReanuda_btnActionPerformed
// TODO add your handling code here:
    hilo1.setEnPausa( !hilo1.getEnpausa());
    if (pausaReanuda_btn.getText().trim().equals("Pausar")){
        pausaReanuda_btn.setText("Reanudar");
    }else{
        pausaReanuda_btn.setText("Pausar");
    }
}//GEN-LAST:event_pausaReanuda_btnActionPerformed

    private void inicializacion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializacion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicializacion_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel igual_lbl;
    private javax.swing.JLabel inicializacion_lbl;
    private javax.swing.JTextField inicializacion_txt;
    private javax.swing.JButton iniciarDetener_btn;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton pausaReanuda_btn;
    private javax.swing.JLabel tope_lbl;
    private javax.swing.JTextField tope_txt;
    private javax.swing.JTextField valor_txt;
    // End of variables declaration//GEN-END:variables

}
