/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3tags;

/**
 *
 * @author chucho
 */
public class Genero {
    
    public static final String[] generos = {
		"Blues",
		"Classic Rock",
		"Country",
		"Dance",
		"Disco",
		"Funk",
		"Grunge",
		"Hip-Hop",
		"Jazz",
		"Metal",
		"New Age",
		"Oldies",
		"Other",
		"Pop",
		"R&B",
		"Rap",
		"Reggae",
		"Rock",
		"Techno",
		"Industrial",
		"Alternative",
		"Ska",
		"Death Metal",	
		"Pranks",
		"Soundtrack",
		"Euro-Techno",
		"Ambient",
		"Trip-Hop",
		"Vocal",
		"Jazz+Funk",
		"Fusion",
		"Trance",
		"Classic",
		"Instrumental",
		"Acid",
		"House",
		"Game",
		"Sound Clip",	
		"Gospel",
		"Noise",
		"Alt Rock",
		"Bass",
		"Soul",
		"Punk",
		"Space",
		"Meditative",
		"Instrumental Pop",
		"Instrumental Rock",
		"Ethnic",
		"Gothic",
		"Darkwave",
		"Techno-Industrial",
		"Electronic",	
		"Pop-Folk",
		"Eurodance",
		"Dream",
		"Southern Rock",
		"Comedy",
		"Cult",	
		"Gangsta",
		"Top 40",
		"Christian Rap",
		"Pop/Funk",
		"Jungle",
		"Native American",
		"Cabaret",
		"New Wave",
		"Psychedelic",
		"Rave",
		"Showtunes",
		"Trailer",
		"Lo-Fi",
		"Tribal",
		"Acid Punk",
		"Acid Jazz",
		"Polka",
		"Retro",
		"Musical",
		"Rock & Roll",
		"Hard Rock",
		"Folk",
		"Folk/Rock",
		"National Folk",
		"Swing",
		"Fast Fusion",
		"Bebob",
		"Latin",
		"Revival",
		"Celtic",
		"Bluegrass",
		"Avantgarde",
		"Gothic Rock",
		"Progressive Rock",
		"Psychedelic Rock",
		"Symphonic Rock",
		"Slow Rock",
		"Big Band",
		"Chorus",
		"Easy Listening",
		"Acoustic",
		"Humour",
		"Speech",
		"Chanson",
		"Opera",
		"Chamber Music",
		"Sonata",
		"Symphony",
		"Booty Bass",
		"Primus",
		"Porn Groove",
		"Satire/Parody",
		"Slow Jam",
		"Club",
		"Tango",
		"Samba",
		"Folklore",
		"Ballad",
		"Power Ballad",
		"Rhythmic Soul",
		"Freestyle",
		"Duet",
		"Punk Rock",
		"Drum Solo",
		"Acapella",
		"Euro-House",
		"Dance Hall",
		"Goa",
		"Drum & Bass",
		"Club-House",
		"Hardcore",
		"Terror",
		"Indie",
		"BritPop",
		"Negerpunk",
		"Polsk Punk",
		"Beat",
		"Christian Gangsta",
		"Heavy Metal",
		"Black Metal",
		"Crossover",
		"Contemporary Chr",
		"Christian Rock",
		"Merengue",
		"Salsa",
		"Thrash Metal",
		"Anime",
		"JPop",
		"Synthpop",
                "Otro" ,
                "RyB" ,
                "Alternativo",
                "Ambiente",
                "Jazz/Funk",
                "Clásica",
                "Clasica",
                "Alternative Rock",
                "Rock Alternativo",
                "Meditación",
                "Meditacion",
                "Étnica",
                "Gótica",
                "Étnico",
                "Gótico",
                "Gotico",
                "Gotica",
                "Etnico",
                "Etnica",
                "Psicodélico",
                "Psicodelico",
                "Rock Gótico",
                "Rock Psicodélico",
                "Rock Gotico",
                "Rock Psicodelico",
                "Musica Criolla",
                "Llanera",
                "Vallenato",
                "Cumbia",
                "Chatarritas",
                "Neo-Folklore",
                "Neo Folklore",
                "Neo Punk",
	};
    
    	public int EmparejarGenero(String descripcion) {
		if (descripcion != null && descripcion.length() > 0) {
			for (int i = 0; i < Genero.generos.length; i++) {
				if (Genero.generos[i].equalsIgnoreCase(descripcion)) {
					return i;
				}
			}
		}
		return 12;
	}
    
}
