/*
 * FigurasV1.java
 *
 * Created on 30 de junio de 2011, 08:14 AM
 */
package figurasv1;

import java.awt.*;

/**
 *
 * @author  adalmarza
 */
public class FigurasV1 extends javax.swing.JFrame {

    /** Creates new form FigurasV1 */
    public FigurasV1() {
        initComponents();
        setSize(400, 200);
        setTitle("Prueba Canvas");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoFigura = new javax.swing.ButtonGroup();
        titulo_lbl = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        panelIZQ = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        posicion_lbl = new javax.swing.JLabel();
        panelDER = new javax.swing.JPanel();
        recta_rbtn = new javax.swing.JRadioButton();
        rectangulo_rbtn = new javax.swing.JRadioButton();
        circulo_rbtn = new javax.swing.JRadioButton();
        ovalo_rbtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("Figuras en Canvas");
        getContentPane().add(titulo_lbl, java.awt.BorderLayout.PAGE_START);

        panel1.setLayout(new java.awt.GridLayout(1, 2));

        panelIZQ.setLayout(new java.awt.GridLayout(2, 1));

        canvas1.setBackground(new java.awt.Color(255, 255, 255));
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvas1MouseMoved(evt);
            }
        });
        panelIZQ.add(canvas1);

        posicion_lbl.setText("Posicion:");
        panelIZQ.add(posicion_lbl);

        panel1.add(panelIZQ);

        panelDER.setLayout(new java.awt.GridLayout(4, 1));

        tipoFigura.add(recta_rbtn);
        recta_rbtn.setText("RECTA");
        recta_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recta_rbtnActionPerformed(evt);
            }
        });
        panelDER.add(recta_rbtn);

        tipoFigura.add(rectangulo_rbtn);
        rectangulo_rbtn.setText("RECTANGULO");
        rectangulo_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangulo_rbtnActionPerformed(evt);
            }
        });
        panelDER.add(rectangulo_rbtn);

        tipoFigura.add(circulo_rbtn);
        circulo_rbtn.setText("CIRCULO");
        circulo_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circulo_rbtnActionPerformed(evt);
            }
        });
        panelDER.add(circulo_rbtn);

        tipoFigura.add(ovalo_rbtn);
        ovalo_rbtn.setText("OVALO");
        ovalo_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalo_rbtnActionPerformed(evt);
            }
        });
        panelDER.add(ovalo_rbtn);

        panel1.add(panelDER);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void canvas1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseMoved
// TODO add your handling code here:
    posicion_lbl.setText("Posicion:(" + evt.getX() + ";" + evt.getY() + ")");
}//GEN-LAST:event_canvas1MouseMoved

private void recta_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recta_rbtnActionPerformed
// TODO add your handling code here:
    Graphics g = canvas1.getGraphics();
    //limpiar el canvas antes de graficar figura seleccionada
    g.clearRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
    int red = (int) (Math.random() * (256));
    int green = (int) (Math.random() * (256));
    int blue = (int) (Math.random() * (256));
    Color color1 = new Color(red, green, blue);
    g.setColor(color1);
    g.drawLine(10, 10, canvas1.getWidth() - 20, canvas1.getHeight() - 20);
}//GEN-LAST:event_recta_rbtnActionPerformed

private void rectangulo_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangulo_rbtnActionPerformed
// TODO add your handling code here:
    Graphics g = canvas1.getGraphics();
    //limpiar el canvas antes de graficar figura seleccionada
    g.clearRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
    int red = (int) (Math.random() * (256));
    int green = (int) (Math.random() * (256));
    int blue = (int) (Math.random() * (256));
    Color color1 = new Color(red, green, blue);
    g.setColor(color1);
    g.drawRect(10, 10, canvas1.getWidth() - 20, canvas1.getHeight() - 20);
}//GEN-LAST:event_rectangulo_rbtnActionPerformed

private void circulo_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circulo_rbtnActionPerformed
// TODO add your handling code here:
    Graphics g = canvas1.getGraphics();
    //limpiar el canvas antes de graficar figura seleccionada
    g.clearRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
    int red = (int) (Math.random() * (256));
    int green = (int) (Math.random() * (256));
    int blue = (int) (Math.random() * (256));
    Color color1 = new Color(red, green, blue);
    g.setColor(color1);
    int radio = Math.min(canvas1.getWidth() - 20, canvas1.getHeight() - 20);
    g.drawOval(10, 10, radio, radio);
}//GEN-LAST:event_circulo_rbtnActionPerformed

private void ovalo_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalo_rbtnActionPerformed
// TODO add your handling code here:
    Graphics g = canvas1.getGraphics();
    //limpiar el canvas antes de graficar figura seleccionada
    g.clearRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
    int red = (int) (Math.random() * (256));
    int green = (int) (Math.random() * (256));
    int blue = (int) (Math.random() * (256));
    Color color1 = new Color(red, green, blue);
    g.setColor(color1);
    g.drawOval(10, 10, canvas1.getWidth() - 20, canvas1.getHeight() - 20);
}//GEN-LAST:event_ovalo_rbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FigurasV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JRadioButton circulo_rbtn;
    private javax.swing.JRadioButton ovalo_rbtn;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelDER;
    private javax.swing.JPanel panelIZQ;
    private javax.swing.JLabel posicion_lbl;
    private javax.swing.JRadioButton recta_rbtn;
    private javax.swing.JRadioButton rectangulo_rbtn;
    private javax.swing.ButtonGroup tipoFigura;
    private javax.swing.JLabel titulo_lbl;
    // End of variables declaration//GEN-END:variables
}
